# SkuBeam — Shopify App Config
client_id = "ae04a4fc032b3a441af7cdde23c94465"
name = "skubeam"
application_url = "https://congressional-strong-length-chances.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "/webhooks/bulk_operations/finish"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders,read_locations"

[auth]
redirect_urls = [ "https://congressional-strong-length-chances.trycloudflare.com/api/auth" ]
